-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
-- 
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
-- Find the sum of all the even-valued terms in the sequence which do not exceed four million.

fibs1 = 0 : 1 : zipWith (+) fibs1 (tail fibs1)
-- Hack: Arbitrary high number to top out list. Should figure out better bound
sum [fibs1!!x | x <- [0..60], fibs1!!x < 4000000, fibs1!!x `mod` 2 == 0]

-- *Main> sum [fibs1!!x | x <- [0..40], fibs1!!x < 4000000, fibs1!!x `mod` 2 == 0]
-- 4613732

